secrets:
    mysqlUser: ENC[AES256_GCM,data:J04u7Q==,iv:K4PskgXBI4aJ/jI4/NcpBabklBfduK9yYXX5ktLbLaQ=,tag:x746qwL7WnB7GKdw/chW7g==,type:str]
    mysqlRootPassword: ENC[AES256_GCM,data:zWcWHQ==,iv:GZvl4e2FW5cHMvcHldWlJEU9NyhtjBqtoKP7pxMH8OA=,tag:jlu4Rk9QD3kapVu/pwGIBQ==,type:str]
    mysqlPassword: ENC[AES256_GCM,data:VpQlcA==,iv:J1bAtq0+rt+XINBsu194UBjJiv70FQKP7cnNgK0OogQ=,tag:nwQ1ereZqjK8BkYnye4Puw==,type:str]
    adminPassword: ENC[AES256_GCM,data:Ym2YVjJpsD5CAi5GUL0=,iv:VrQvXhL6g3MHqZyiSiBimKgjCyWE47SvhulMrwJzNvg=,tag:wx3rpdHOAL/8IlOAR6ZOMg==,type:str]
    hrPassword: ENC[AES256_GCM,data:aIvE4ye9sSqFNT8=,iv:Zk1HY3CjdFJHLw2C9+kQwdXXY+B0sppENtuBOeM5NgE=,tag:plqhUqy6soUDmSZLQG/svA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQ3FCYTFIdG0wdkt0ZlBa
            MnN4NWNuWDhsd3pDNTlsM3AwSXlXb2JmdVVVCm4xWDlWcU5NaGM2RGwvZEhid3B0
            a2JBMmd4MnRHaTlwa0hZZHFkNTc1bkUKLS0tIDZ0bWJrMmpLNExJV2JNenlOZHE0
            Y0JyeU9QeDBPWGRMTFVDbkw5SzNsSGcKM8UeA16kScqcm2YjlKiAbKouDOmhTaWb
            OH4QIx+QVabukFW0fX0T2BxVM8UeuCdHqhY0q7aVjNEDSezFQsx9Lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5hh3xhe33efl33j2nylerg59g3em5l22m9hxlhg9hrvfkv3afuq98arn2
    lastmodified: "2026-09-15T17:31:51Z"
    mac: ENC[AES256_GCM,data:tBxiUr8Rj8mWrU36L2Kt6QhNdjLEhKJpAlkl9G/KVmr/r096mTjA5jKxIF703cnIhZKyqhzwfx+LJ/Xqckhu2p8CgFnZktWvT6ErfupIrTH388bGleRfnv0mHtr4CD2I40bCef/ZDbSDF85qHt4gyik7RswyFeDcCfV/2PItfBk=,iv:tZa2VaUUqliYdN/VLHmqieqBn7G6COcPDYdg2MJEQ6s=,tag:hvRN+Lxbl0qtI0q2jfXgXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
