secrets:
    mysqlRootPassword: ENC[AES256_GCM,data:cTxXoA==,iv:UfUw9tY+Fra1O/uOEko44Et0YjRE1UodnH1mwRkZAp4=,tag:1dwzERB6u+jW/+CwPo+tsA==,type:str]
    adminPassword: ENC[AES256_GCM,data:YVX9+YUog0TydvrfdPM=,iv:nBzLG/CqRuXQoR7DJ9LS1u9+7d2P+KFVMHOtSVANt/U=,tag:B0CYub5S6slM1/+uFxfLPQ==,type:str]
    hrPassword: ENC[AES256_GCM,data:v0hwOFBFdu4m7hA=,iv:DVUrx3FFZjYzk2t32FoYfmuK9JRYEMkTre7KAfdGeOg=,tag:DoSnuIkPm2vLRG1HwcZYnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0M3hpc01vQWNlcXk2RzQr
            WUxpZnlhSGRNUXJRK2R2SmwrRy9SNHZqdlFrCnFoam1XS0dBd0ZOeGJzSGFOSkdl
            UmROWVZ5ajF3MFNMbktSdjZKdDhhenMKLS0tIDBpTU1IWlZNUVF3WU9lc2hlckJl
            a1c5aWVwN2hmN1hhYkFpRlUwUkh0bzAKnU7V4g7lmkLo+N2Z+H0E3xomO9NgjV1D
            dSINk902Lczlbco+GwRidkOe5dyXRpOQj0mnzbFj6Vtv6ROn/7LC+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5hh3xhe33efl33j2nylerg59g3em5l22m9hxlhg9hrvfkv3afuq98arn2
    lastmodified: "2026-09-16T11:22:07Z"
    mac: ENC[AES256_GCM,data:LI5PA0kqKqdC/ar4L1lgZ8NmW3nlzsxgKMZNb0IXVfZbbB7k18ROrzRVJ87OakJ6DMdgt9dTwkwQY+dLR/HpPW1ENiVCsujPxYpUmc5A2CJZN76sFcIxKhN1NuGlOP3SJMLVGR9/zYcO9IFRFe3n1x/Sv62/eJfq7xAr9wMm6FY=,iv:4BuO5Hluc65qK4LTdufv0IqkjB6Iez4fR6bzWlIO7HE=,tag:SpbV8jicNlcSquGquW6y6A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
