kind: ConfigMap
apiVersion: v1
metadata:
  name: configmaps-server
  namespace: {{ .Release.Namespace }}
data:
  ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
  COOKIE_SECURE: "false"
  COOKIE_SAMESITE: "lax"
  SQL_ECHO: "false"
 
  DEFAULT_HR_EMAIL: "hr@hrmapp.com"
  DEFAULT_HR_ROLE: "hr_manager"
  DEFAULT_ADMIN_EMAIL: "admin@hrmapp.com"
  DEFAULT_ADMIN_ROLE: "admin"