apiVersion: v1
kind: Secret
metadata:
  name: secrets-server
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.secrets.mysqlUser | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | quote }}
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_DB: hrm_database

  DEFAULT_ADMIN_USER: admin
  DEFAULT_ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  DEFAULT_HR_USER: hr
  DEFAULT_HR_PASSWORD: {{ .Values.secrets.hrPassword | quote }}
