kind: Service
apiVersion: v1
metadata:
  name: server-service #Had to change in accordance to what nginx upstream expects
  namespace: {{ .Release.Namespace }}
  labels: 
    app: server
spec: 
  type: ClusterIP
  selector: 
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: {{ .Values.server.containerPort }}
    