export const buildEmployeePayload = (formData, departments) => ({
  first_name: formData.firstName.trim(),
  last_name: formData.lastName.trim(),
  email: formData.email.trim().toLowerCase(),
  phone: formData.phone.trim(),
  address: formData.address.trim() || null,
  hire_date: formData.joinDate || null,
  date_of_birth: formData.dateOfBirth || null,
  department_id: departments.find((dep) => dep.name === formData.department)?.id || null,
  position: formData.position.trim(),
  salary: Number(formData.salary) || 0,
  manager: formData.manager.trim() || null,
  bank_name: formData.bankName.trim() || null,
  bank_branch_name: formData.bankBranchName.trim() || null,
  bank_account_name: formData.bankAccountName.trim() || null,
  bank_account_number: formData.bankAccountNumber.trim() || null,
  bank_swift_code: formData.bankSwiftCode.trim() || null,
  emergency_contact_name: formData.emergencyContactName.trim() || null,
  emergency_contact_relationship: formData.emergencyContactRelationship.trim() || null,
  emergency_contact_phone: formData.emergencyContactPhone.trim() || null,
  skills: formData.skills.length ? formData.skills.join(', ') : null,
  status: formData.status || 'active',
  is_active: (formData.status || 'active') === 'active'
})
