#service
apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: hrm-namespace
spec:
  selector: 
    app: mysql-db
  ports:
    - port: 3306
  clusterIP: None

---

#stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stateful-set
  namespace: hrm-namespace
spec:
  selector: 
    matchLabels:
      app: mysql-db
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          envFrom:
            - secretRef: 
                name: hrm-mysql-secrets
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]      
        resources:
          requests: 
            storage: 2Gi 

