apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: client
spec:
# restricts typical isolating of service
  type: NodePort
  selector:
    app: client
  ports:
    - name: http
      protocol: TCP
      #public facing port opens at 80
      port: 80
      #tells service exactly what port to hit on application container
      targetPort: {{ .Values.client.containerPort }}
      nodePort: 32080