#central config file for values

global:
  environment: local

client:
  replicas: 1
  image:
    repository: 767397806614.dkr.ecr.us-east-1.amazonaws.com/hrm-infra-app
    tag: client-latest
  imagePullPolicy: IfNotPresent
  containerPort: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

server:
  replicas: 1
  image:
    repository: 767397806614.dkr.ecr.us-east-1.amazonaws.com/hrm-infra-app
    tag: server-latest
  imagePullPolicy: IfNotPresent
  containerPort: 8000
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

#Dynamic ingestion of sensitive credentials using --set flag during deployment.
secrets:
  mysqlUser: hrm_user
  mysqlPassword:
  adminPassword:
  hrPassword:

mysql:
  replicas: 1
  image: mysql
  tag: "8.0"
  storage: "2Gi"
