#service
apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: {{ .Release.Namespace }}
spec:
  selector: 
    app: mysql-db
  ports:
    - port: 3306
  clusterIP: None

---

#stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-stateful-set
  namespace: {{ .Release.Namespace }} 
spec:
  selector: 
    matchLabels:
      app: mysql-db
  serviceName: "mysql"
  replicas: {{ .Values.mysql.replicas }}
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image }}:{{ .Values.mysql.tag }}" 
          envFrom:
            - secretRef: 
                name: hrm-mysql-secrets
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data 
              mountPath: /var/lib/mysql 
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]      
        resources: 
          requests: 
            storage: {{ .Values.mysql.storage | quote }}

