apiVersion: v1
kind: Secret
metadata:
  name: hrm-mysql-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlPassword | quote }}
  MYSQL_DATABASE: hrm_database
  MYSQL_USER: {{ .Values.secrets.mysqlUser | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | quote }}